spring.application.name=budgetly

spring.datasource.url=jdbc:postgresql://localhost:5433/budgetly
spring.datasource.username=budgetly_user
spring.datasource.password=budgetly_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false